// Integration test between Frontend ColonyApiClient and Java Backend
import { colonyApiClient } from './src/api/ColonyApiClient.js';

async function runIntegrationTest() {
  console.log('================================================================');
  console.log('  TESTING FRONTEND ↔ JAVA BACKEND INTEGRATION (6-SOL LIFECYCLE) ');
  console.log('================================================================\n');

  // Step 0: Reset backend to clean state
  console.log('--> Resetting simulation to Sol 1...');
  const s0 = await colonyApiClient.resetSimulation();
  if (!s0) {
    throw new Error('Failed to connect to Java backend at http://localhost:8080');
  }
  console.log(`✓ Sol: ${s0.sol}, Status: ${s0.status}`);

  // Sol 1: Normal Operations
  console.log('\n[SOL 1 — NORMAL OPERATIONS]');
  const s1 = await colonyApiClient.fetchState();
  console.log(`  Status: ${s1.status}`);
  console.log(`  Power:  ${s1.resources.Power.current} / ${s1.resources.Power.max} kW (Balance: ${s1.resources.Power.balance} kW/Sol)`);
  console.log(`  Facilities: ${s1.facilities.length} active (Habitat is ${s1.facilities[0].status})`);
  if (s1.sol !== 1 || s1.status !== 'STABLE') throw new Error('Sol 1 verification failed');

  // Sol 2: Inject Dust Storm
  console.log('\n[SOL 2 — DUST STORM DETECTED]');
  const s2_event = await colonyApiClient.triggerEvent('dust_storm', 2.0);
  console.log(`  Active Event: ${s2_event.activeEvents[0].name} (${s2_event.activeEvents[0].severity})`);
  
  const s2 = await colonyApiClient.stepSol();
  console.log(`  Advanced to Sol: ${s2.sol}`);
  console.log(`  Power Generation dropped: Balance = ${s2.resources.Power.balance} kW/Sol`);
  if (s2.sol !== 2) throw new Error('Sol 2 advance failed');

  // Sol 3: Autonomous Management System activates
  console.log('\n[SOL 3 — AUTONOMOUS MANAGEMENT ACTIVATES]');
  const s3 = await colonyApiClient.stepSol();
  console.log(`  Advanced to Sol: ${s3.sol}`);
  console.log(`  Management Actions generated by Java (${s3.managementResponse.length} actions):`);
  for (const act of s3.managementResponse) {
    console.log(`    • ${act.facility.padEnd(22)} ${act.transition.padEnd(12)} -> Saved: ${act.saved} kW [${act.action}]`);
  }
  
  // Verify Life Support protected invariant
  const habitatAction = s3.managementResponse.find(a => a.facility.includes('Habitat'));
  if (!habitatAction || habitatAction.action !== 'PROTECTED') {
    throw new Error('Life Support was not PROTECTED at 100%!');
  }

  // Engage backup generator
  console.log('  Engaging auxiliary backup power...');
  const s3_backup = await colonyApiClient.toggleBackupPower();
  console.log(`  Backup Generator: Active = ${s3_backup.recovery.backupActive}`);

  // Sol 4: Dust storm dissipates
  console.log('\n[SOL 4 — WEATHER CLEARING]');
  const s4 = await colonyApiClient.stepSol();
  console.log(`  Advanced to Sol: ${s4.sol}`);
  console.log(`  Active Events remaining: ${s4.activeEvents.length}`);

  // Sol 5: Rehabilitation (+25%/Sol)
  console.log('\n[SOL 5 — GRADUAL REHABILITATION]');
  const s5 = await colonyApiClient.stepSol();
  console.log(`  Advanced to Sol: ${s5.sol}`);
  for (const fac of s5.facilities) {
    console.log(`    • ${fac.name.padEnd(24)} : ${fac.operatingLevel}% [${fac.status}]`);
  }

  // Sol 6: Equilibrium Restored
  console.log('\n[SOL 6 — EQUILIBRIUM RESTORED]');
  const s6 = await colonyApiClient.stepSol();
  console.log(`  Advanced to Sol: ${s6.sol}, Status: ${s6.status}`);
  for (const fac of s6.facilities) {
    console.log(`    • ${fac.name.padEnd(24)} : ${fac.operatingLevel}% [${fac.status}]`);
  }
  if (s6.status !== 'STABLE') throw new Error('Colony status did not return to STABLE');

  // Reset simulation for clean user session
  console.log('\n--> Resetting simulation to Sol 1 for clean user session...');
  await colonyApiClient.resetSimulation();

  console.log('\n================================================================');
  console.log('  INTEGRATION TEST PASSED: 100% SUCCESS                          ');
  console.log('  JAVA BACKEND IS VERIFIED AS SINGLE SOURCE OF TRUTH!            ');
  console.log('================================================================\n');
}

runIntegrationTest().catch(err => {
  console.error('❌ Integration test failed:', err);
  process.exit(1);
});
